### ISSUE TITLE
Test V3 - 2016 : Création d'une relation élève - élève

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#100]
Lorsqu'on créé une relation à partir d'un utilisateur élève, cette relation est créée à la fois dans les relations "A les relations Elève suivantes" et "A les relations Adulte suivantes".
Seule la relation Elève a l'icône poubelle. Lors de la suppression de la relation, celle-ci est bien supprimée à la fois dans les relations Elèves et les relations Adultes.

**Comment by HuguesGithub** [comment]
Ca n'est pas un bug à proprement parler.
Il n'est pas prévu dans le code de pouvoir supprimer une telle relation. Le bouton n'est jamais affiché à cet endroit.

Est-ce un oubli lors du développement, ou y avait-il une "vraie raison". A voir.

**Comment by HuguesGithub** [comment]
Interface corrigée. Problème plus existant.
