### ISSUE TITLE
Test V3 - 2016 : Gestion des utilisateurs - messages d'erreurs

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#101]
(1) Lorsqu'on veut créer une relation avec un élève et que l'ID ENT renseigné est celui d'un utilisateur d'un autre profil, appartenant ou non à l'établissement, le message d'erreur affiché est :
Une erreur s'est produite : [Requête incorrecte : l'élève n'appartient pas à l'établissement]
--> à remplacer par : 
Une erreur s'est produite : Requête incorrecte : l'utilisateur n'est pas un élève de l'établissement

(2) Lorsqu'on veut créer en doublon un compte utilisateur, le message d'erreur affiché est :
Une erreur s'est produite : Requête incorrecte: login is already taken 
--> à remplacer par : 
Une erreur s'est produite : Requête incorrecte : le login est déjà utilisé

**Comment by HuguesGithub** [comment]
Point [2] géré par la #122. Il n'est plus possible de créer un compte utilisant un login déjà utilisé.
Point [1] : Problématique Annuaire, à modifier à terme (non bloquant)

**Comment by TestsCGI** [comment]
Point 2 : OK

**Comment by HuguesGithub** [comment]
Gérer le point [1].

**Comment by HuguesGithub** [comment]
Traité et poussé en dev.
A noter, ce contrôle ne survient que via un profil chef d'établissement.
Le contrôle levant cette erreur n'est pas fait pour les profils admin technique.

**Comment by HuguesGithub** [comment]
Tag #1.3.22

**Comment by TestsCGI** [comment]
ok
