### ISSUE TITLE
Test V3 - 2016 : Gestion des utilisateurs - mise à jour de la couleur ID ENT suite réinitialisation mot de passe

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#102]
Dans la liste des utilisateurs, l'ID ENT d'un utilisateur est affiché en rouge.
Suite à la réinitialisation de son mot de passe et, suite à la connexion de cet utilisateur et à la modification de son mot de passe, ID ENT reste en rouge "mot de passe par défaut non changé"

**Comment by HuguesGithub** [comment]
Sur l'interface de l'admin panel, la réinitialisation du mot de passe ne repasse pas l'id en rouge.

Après analyse, lors de la réinitialisation du mot de passe, le champ "change_password" n'est pas repassé à false.

Je suppose que le même problème a lieu lorsque le mot de passe est changé, le champ "change_password" n'est pas renseigné à true.

C'est une problématique annuaire.

**Comment by HuguesGithub** [comment]
TODO : Vérifier que le correctif effectué sur l'anuaire est bien pris en compte sur l'interface.

**Comment by TestsCGI** [comment]
Lors de la réinitialisation du mot de passe, il faut rafraîchir l'admin panel pour que l'ID ENT s'affiche en rouge "mot de passe par défaut non changé"

**Comment by TestsCGI** [comment]
Rafraîchissement de la page toujours à faire pour que l'ID ENT s'affiche en rouge "mot de passe par défaut non changé"
