### ISSUE TITLE
Test V3 - 2016 : Gestion groupes / classes - Nb élèves / enseignants différents entre la liste et la fiche de données de la classe

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#103]
Depuis la liste des classes, on note le nombre d'élèves et d'enseignants d'une classe.
On clique sur le nom de la classe et le nombre d'élèves et d'enseignants peuvent ne pas être cohérents avec les nombres de la liste.

**Comment by HuguesGithub** [comment]
La différence au niveau du nombre d'élèves est probablement dû à un problème au niveau des données et ne devrait pas survenir avec des données "officielles". Toutefois, il est nécessaire de rester vigilant sur le sujet.
La différence au niveau du nombre d'enseignants vient d'un problème de requête côté Annuaire. Les enseignants ayant plusieurs matières associées sont comptés autant de fois. La requête en question va être modifiée pour retourner le bon nombre d'enseignants.

**Comment by TestsCGI** [comment]
Le nombre d'enseignants n'est plus comptabilisé en fonction du nombre de matières enseignées
--> OK
