### ISSUE TITLE
Test V3 - 2016 : Recherche des groupes / classes / groupes libres

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#106]
La recherche ne s'effectue pas uniquement sur les champs 
- libellé pour les groupes / classes / groupes libres
- description pour les groupes et les classes
mais aussi sur des données non visibles pour l'utilisateur (ex. ID ENT)

**Comment by HuguesGithub** [comment]
Mise en palce filtre sur les colonnes visibles des 3 ensembles.
Classes : Nom / Description / Niveau
Groupes d'élèves : Nom / Description
Groupes libres : Groupe libre

**Comment by TestsCGI** [comment]
Test OK
