### ISSUE TITLE
Test V3 - 2016 : Gestion des groupes / classes - Création en doublon d'un groupe / classe / groupe libre

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#107]
Lors de la création en doublon d'une classe le message d'erreur affiché est :
Une erreur s'est produite : Requête incorrecte : Mysql2::Error: Duplicate entry '42002-3E' for key 'unique_index"
--> à remplacer par 
Une erreur s'est produite : Requête incorrecte : une classe du même nom existe déjà

Idem pour la création d'un groupe

Pour la création d'un groupe libre en doublon (même nom - administrateur différent). Il n'y a pas de message d'erreur. Au contraire s'affiche un message de confirmation de la création : "Le groupe libre a bien été ajouté" alors que le doublon n'est pas créé.

**Comment by TestsCGI** [comment]
Pour l'association d'utilisateurs à un groupe libre, si un utilisateur est déjà associé à ce groupe, il continue d'apparaître dans la liste des utilisateurs pouvant être associé à ce groupe.
Lorsqu'il est ajouté pour la seconde fois, un message de confirmation de l'ajout s'affiche : "L'utilisateur VBW63622 est ajouté au groupe."

**Comment by HuguesGithub** [comment]
Il n'est plus possible de créer de regroupements portants le même nom (dans le même établissement pour les classes et les groupes d'élèves.

**Comment by TestsCGI** [comment]
OK
