### ISSUE TITLE
Test V3 - 2016 : Création de groupes libres - Sélection administrateur

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#108]
Lors de la création d'un groupe libre, un administrateur doit être choisi dans la liste des utilisateurs proposés.
Dans le cas de 2 utilisateurs homonymes et de même profil, un seul utilisateur est proposé. On ne sait pas  à qui il peut correspondre car le login les distinguant n'est pas affiché.

**Comment by HuguesGithub** [comment]
Le login n'est pas disponible comme information à cet endroit.
Solution temporaire : Affichage de l'identifiant technique (id_ent)
Solution définitive : Fournir depuis l'Annuaire le login, pour qu'il puisse être affiché.

**Comment by TestsCGI** [comment]
Test ok.
Evolution reportée également lors de l'édition d'un groupe libre existant et la modification de l'admin.
