### ISSUE TITLE
Test V3 - 2016 : Groupes libres - Suppression utilisateurs / groupes libres

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#109]
Après avoir sélectionné un ou plusieurs utilisateurs associés à un groupe libre et, après avoir cliqué sur le bouton Supprimer, la suppression n'est pas effectuée.

**Comment by TestsCGI** [comment]
La suppression d'un utilisateur sur un groupe libre ne fonctionne pas non plus lorsque c'est l'enseignant qui souhaite s'enlevait d'un groupe libre dont il fait partie

**Comment by TestsCGI** [comment]
Lors de la suppression d'un groupe libre, un message d'erreur s'affiche : 
Une erreur s'est produite : Requête incorrecte: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`annuairev3`.`membre_regroupement_libre`, CONSTRAINT `fk_user_has_regroupement_libre_regroupement_libre1` FOREIGN KEY (`regroupement_libre_id`) REFERENCES `regroupement_libre` (`id`))

**Comment by HuguesGithub** [comment]
Première entrée : Correctifs mis en place. La mécanique de sélection utilise le même code que l'écran précédant listant les groupes libres, seulement, la clé pour les uns et "user_id" et pour les autres "id". Prise en compte.

Deuxième entrée : Vérifier la problématique, mais a priori, problème similaire au précédent et réglé en même tems.

Troisième entrée : Problème connu. Il vient du fait que le groupe possède des utilisateurs. Il est nécessaire de supprimer les utilisateurs avant de supprimer le groupe.

**Comment by HuguesGithub** [comment]
Troisième entrée : problème partiellement corrigé. La suppression se fait bien, mais on rencontre des requêtes url qui retournent des erreurs 404.

Still wip.

**Comment by TestsCGI** [comment]
Il est maintenant possible pour 
- un admin de supprimer un ou plusieurs utilisateurs d'un groupe libre
- un enseignant de s'enlever d'un groupe libre
Lors de la suppression d'un groupe libre : les utilisateurs sont d'abord supprimés puis il est possible de supprimer le groupe libre. Il faut procéder en 2 temps pour supprimer le groupe
Dans le cas d'une suppression de plusieurs groupes libres : les premiers groupes et utilisateurs associés sont supprimés ainsi que les membres du dernier groupe. Reste à supprimer le dernier groupe.

**Comment by HuguesGithub** [comment]
On a un problème qui semble être revenu.
Depuis localhost : 
https://v3dev.laclasse.com/api/etablissements/0690078K/groupes_libres/50/membres/VBK60419

"Blocage d’une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://v3dev.laclasse.com/api/etablissements/0690078K/groupes_libres/50/membres/VBK60419. Raison : méthode manquante dans l’en-tête « Access-Control-Allow-Methods »."

**Comment by HuguesGithub** [comment]
Ca semble fonctionner en prod. Cependant, on a des requêtes de Get qui reveinnent en erreur puisque les entrées sont supprimées.
A améliorer.
