### ISSUE TITLE
Test V3 - 2016 : ajout d'utilisateurs d'un autre établissement

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#110]
Seuls les 5 premiers établissements de liste des établissements sont accessibles.
Si l'établissement de rattachement de l'utilisateur connecté ne fait pas partie de ces 5 premiers établissements, alors il n'est plus possible de le sélectionner à nouveau. Il n'apparaît pas dans la liste des établissements proposés.

**Comment by HuguesGithub** [comment]
Le problème vient du fait que la récupération de la liste des établissements à par défaut une pagination, ici définie à 5 éléments.

Hypothèse n° 1 : Récupérer l'ensemble des établissements. Problème, ça peut faire beaucoup de données, surtout si chacun amène tout son contenu. Il faudrait donc une requête qui récupère que le strict minimum.
Hypothèse n°2 : Mettre en place une sorte de pagination dans la combobox. Sans doute pas simple à effectuer techniquement.

**Comment by HuguesGithub** [comment]
Correctif mis en place.
On a la liste des établissements disponibles, avec l'ajout d'un filtre pour la parcourir plus aisément.

**Comment by TestsCGI** [comment]
Test OK
