### ISSUE TITLE
Test V3 - 2016 : Accès aux ressources numériques

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#111]
Dans ressources numériques, lorsqu'on clique sur le lien présent sur le nom de la ressource, celle-ci ne s'affiche pas (sauf avec IE) :
- avec Chrome : affichage du bandeau du portail + page blanche
- avec Firefox : rien ne se passe. On reste sur la page de l'admin panel

**Comment by HuguesGithub** [comment]
Doublon #123

**Comment by TestsCGI** [comment]
Tests OK
