### ISSUE TITLE
suppression impossible d'un groupe d'élèves qui a été alimenté automatiquement l'an dernier

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#114]
![capture du 2016-08-29 11-38-17](https://cloud.githubusercontent.com/assets/7963908/18047472/6caac31a-6ddd-11e6-9ef3-e50a59cd8c8a.png)

**Comment by heleroy** [comment]
tu peux tester (pour reproduire le souci) avec le groupe d'élèves 3AGL9GR1 (1er de la liste) du clg V. Grignard

**Comment by HuguesGithub** [comment]
On peut supprimer les classes et groupes automatiquement alimentés avant le dernier 15 juillet.
