### ISSUE TITLE
[admin etab / list users] 'cocher tous' ne tiens pas compte du filtrage

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#117]
sont cochés mêmes les utilisateurs non affichés

**Comment by HuguesGithub** [comment]
Correctif apporté. Les éléments filtrés ne sont plus sélectionnés lors d'un check_all.
Par ailleurs, la modification de la valeur du filtre entraîne une désélection de tous les éléments cochés.
