### ISSUE TITLE
[admin etab / list users] filtrage et pagination

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#118]
le filtrage se fait après le découpage en pages donc une 'page' a moins d'users que prévu

**Comment by HuguesGithub** [comment]
Le filtrage a été supprimé. Il ne se faisait que sur les 3 premièrs caractères, puis on lançait une requête pour mettre à jour les données.
Le comportement n'était pas cohérent, ni facilement compréhensible.

Par contre, ajout d'un requêtage sur le onBlur du champ en question, afin de simuler un filtrage, et en ayant récupéré les données correspondantes.
