### ISSUE TITLE
La suppression de la photo d'établissement n'est pas possible excepté en ajoutant une nouvelle photo

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#119]
![capture du 2016-09-08 11-58-17](https://cloud.githubusercontent.com/assets/7963908/18345397/953a3faa-75bb-11e6-831d-b9bbcde1b57a.png)

**Comment by HuguesGithub** [comment]
L'api côté Annuaire n'existe pas. A traiter en premier lieu.

**Comment by dlacroix** [comment]
Plus de bannière
