### ISSUE TITLE
interdire la création d'un login avec un point "."

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#120]

**Comment by HuguesGithub** [comment]
Il y a bien un contrôle indiquant que le login n'est pas valide, mais rien n'empêche la validation et la création.

**Comment by HuguesGithub** [comment]
Idem #122

**Comment by HuguesGithub** [comment]
La saisie du login étant limité au SuperAdmin, on peut s'attendre à ce qu'il fasse attention à ce qu'il fait.
Contrôle non mis en place.
