### ISSUE TITLE
Enregistrement d'une application et clef d'application invalide

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#121]
Il semble que lorsque l'on crée une application dans l'admin panel, un retour à la ligne est ajouté dans l'application_key inséré dans la base.

Il faut qualifier ce problème et le résoudre.

**Comment by HuguesGithub** [comment]
Non reproduit en l'état, investigation en cours.

**Comment by HuguesGithub** [comment]
Toujours pas reproduit et depuis le passage à la v4, ça ne semble plus se produire.
