### ISSUE TITLE
avertir si le login est déjà pris ou libre sur la fenêtre de création de comptes

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#122]
Aucun avertissement pour l'instant au moment de créer le compte. C'est une fois qu'on valide la création que l'on a un message d'erreur donc il faut tout refaire et tente un autre login en espérant qu'il soit dispo...
![capture du 2016-09-15 11-56-34](https://cloud.githubusercontent.com/assets/7963908/18545965/c18c6cc4-7b3b-11e6-8331-51e403aaa338.png)

**Comment by HuguesGithub** [comment]
Il y a bien une alerte. Mais ça n'empêche pas la validation. Par contre l'utilisateur n'est pas créé.

**Comment by HuguesGithub** [comment]
Si la zone est la dernière saisie, le contrôle marche. Mais si un autre champ est modifié, le contrôle ne semble pas être pris en compte.

**Comment by dlacroix** [comment]
fait
