### ISSUE TITLE
Suppression d'un élève d'une classe et non mise à jour des élèves dispos

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#127]
En tant qu'admin d'établissement. Si on supprime un élève d'une classe, il ne revient pas dans la liste des élèves disponibles à droite.

**Comment by HuguesGithub** [comment]
Pour propager des events de façon descendante, on doit utiliser broadcast et pas emit.

**Comment by HuguesGithub** [comment]
Confère #94

**Comment by HuguesGithub** [comment]
Tag #1.3.22

**Comment by dlacroix** [comment]
ok c'est validé
