### ISSUE TITLE
Liste des enseignants disponibles

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#128]
En tant qu'administrateur d'établissement. Dans l'interface d'ajout d'un enseignant dans une classe, le compteur d'enseignant disponible ne correspond pas aux enseignents disponibles juste en dessous.

**Comment by HuguesGithub** [comment]
Le compteur pointait vers la liste complète des enseignants, et pas sur la liste des enseignants disponibles.
