### ISSUE TITLE
Améliorer la recherche au niveau de l'ajout d'utilisateur à son groupe libre

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#136]
ajouter un filtre par classe, profil ? pour permettre l'ajout des élèves de toute une classe (à cocher un par un... ou si possible avec une case à cocher la totalité des résultats correspondant à la recherche filtrée).

**Comment by HuguesGithub** [comment]
Implémenté pour les groupes d'élèves.
Voir s'il est possible de faire de même sur les groupes libres, mais je ne suis pas certain que la notion de classe soit présente dans la liste retournée...

**Comment by TestsCGI** [comment]
Issue mère : #159

**Comment by TestsCGI** [comment]
Évolutions groupes libres rentrée 2017 :
Vérifier l'ajout des utilisateurs en filtrant d'abord sur l'établissement puis, leur profil et, pouvoir ajouter des regroupements entiers comme pour la gestion des membres des classes : est-ce que la même API peut être utilisée ?

**Comment by HuguesGithub** [comment]
Mise en place d'une mécanique similaire à l'interface Utilisateurs.
