### ISSUE TITLE
Impossible d'éditer un utilisateur

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#137]
Dans la Gestion des utilisateurs en admin TECH. Si on sélectionne un utilisateur pour clic sur éditer. Rien ne se passe à part des problèmes JS

**Comment by HuguesGithub** [comment]
Il semblerait, que le fait que la date de naissance ne soit pas renseignée, pose problème.
Il est d'ailleurs plus possible de créer un utilisateur sans saisir de date de naissance.
Je pense que la crainte d'obligation de renseigner ce champ ne soit présente qu'au niveau de la table SQL.

**Comment by HuguesGithub** [comment]
Finalement, une méthode javascript était appliquée sur la date de naissance.
Etant null, on avait une erreur qui bloquait le déroulement du script.
Corrigé et livré en production.
