### ISSUE TITLE
Formulaire de création d'utilisateur et adresse email

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#138]
Si on renseigne une adresse email, elle est prise pour l'adresse postale.

**Comment by HuguesGithub** [comment]
La requête précédente renseignait le champ adresse avec l'adresse mail. Mais a priori, c'est le champ adresse de emails qui doit l'être.
Il faut donc probablement une requête qui soit plus orientée comme suit : 
{"nom":"Joneaux","prenom":"Hugues","login":"jhugues14","password":"jhugues14","emails":{"type":"Ent"
,"adresse":"hugues.joneaux1@laclasse.com"},"profil":"ENS","etablissement":"0699990Z","date_naissance"
:"01/01/1970"}

**Comment by dlacroix** [comment]
Le service existe déjà mais c'est:
{"nom": "Joneaux", "prenom": "Hugues","login": "jhugues14", "password": "jhugues14", "emails":[{"type":"Ent", "adresse":"hugues.joneaux1@laclasse.com", "principal":true}], "profil": "ENS", "etablissement": "0699990Z", "date_naissance": "01/01/1970"}

**Comment by HuguesGithub** [comment]
Prise en compte des crochets pour emails :
{"nom":"Joneaux","prenom":"Hugues","login":"jhugues14","password":"jhugues14","emails":[{"type":"Ent"
,"adresse":"hugues.joneaux1@v3dev.laclasse.com","principal":true}],"profil":"ENS","etablissement":"0699990Z"}
La date de naissance n'étant pas forcément renseignée, le champ n'est pas forcément communiqué.
