### ISSUE TITLE
afficher la liste des membres du groupe libre dans la fenêtre "éditer le groupe libre" pour nommer un autre admin

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#139]

**Comment by HuguesGithub** [comment]
Pris en compte.

A noter, qu'en s'appuyant sur la liste des membres du groupe libre, on n'a plus accès à l'information relative au profil du membre. Dans un groupe libre, cette notion n'existe pas.
Aussi, le contrôle qui reposait sur cette information et qui empêchait un élève d'être nommé administrateur a été supprimé. C'est à l'administrateur de faire attention lorsqu'il utilise cette fonctionnalité, de ne pas sélectionner un élève.
