### ISSUE TITLE
Permettre à un personnel de pouvoir s'ajouter un profil (enseignant) dans un autre établissement que le sien

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#140]
via la fenêtre "mon profil", ajouter la combo box de la liste des établissements. C'est utile pour les cas de changements ou d'ajout d'établissement de le cas les établissements non alimentés automatiquement (primaire notamment).

**Comment by HuguesGithub** [comment]
Pris en compte et modifié.
Le contrôle suivant a été mis en place :

Un Administrateur Technique peut accorder n'importe quel profil, à n'importe quel utilisateur de n'importe quel établissement.

Un Administrateur d'Etablissement peut accorder n'importe quel profil, à n'importe quel utilisateur dans son établissement.

Un Administrateur d'Etablissement ou un Enseignant peut s'accorder n'importe quel profil à l'exception d'Adminstrateur d'Etablissement dans n'importe quel établissement.
