### ISSUE TITLE
Groupe libre : la modification du libellé d'un groupe existant entraîne celle de l'admin du groupe

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#141]
Une fois la modification du libellé du groupe libre existant enregistré, l'utilisateur connecté perd ses droits d'amin du groupe libre.
C'est l'utilisateur ayant le même id (technique) que celui du groupe à qui sont attribués les droits d'admin du groupe libre. 
L'ancien admin continue d'appartenir au groupe.
Ex. groupe libre renommé "GLnouveau". L'utilisateur principal test a perdu ses droits d'administrateur au profit de l'utilisateur Zoé Birost.
Cf. copie d'écran ci-jointe
[modif nom gl et chgt admin.docx](https://github.com/laclasse-com/service-admin-panel/files/558686/modif.nom.gl.et.chgt.admin.docx)

**Comment by HuguesGithub** [comment]
A l'affichage de la fenêtre d'édition, l'administrateur actuel est repris. Au lieu de reprendre son identifiant, c'était l'identifiant du groupe qui était repris.
C'est corrigé.

Cependant, l'identifiant de l'administrateur du groupe n'est pas disponible dans les données remontées par l'API. Aussi, lors de la modification du libellé, il est nécessaire de resélectionner l'utilisateur actuel pour revalider son identifiant.
A améliorer.

**Comment by HuguesGithub** [comment]
Corrigé et livré.
