### ISSUE TITLE
améliorer les listes déroulantes de recherche d'établissement pour le profil tech

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#142]
Ajouter le code UAI ou la commune de l'établissement car il y a beaucoup d'écoles primaires qui n'ont pas de nom spécifiques et elles sont alors toutes appelées "Ecole primaire" dans la liste donc c'est impossible de les différencier à part en allant dessus et en vérifiant le code UAI ensuite...

**Comment by heleroy** [comment]
Du coup, pour l'exemple de l'école primaire de Cailloux sur Fontaine, j'ai ajouté la mention "DE CAILLOUX" à la suite de "ECOLE PRIMAIRE" pour la reconnaître.

**Comment by HuguesGithub** [comment]
Ce sera le code_uai car le nom de la commune n'est pas disponible.

**Comment by HuguesGithub** [comment]
Feature livré.
