### ISSUE TITLE
Ajouter un export CSV des utilisateurs d'un établissement

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#143]
Pour divers usages, c'est pratique. Par exemple pour la synchro avec SACOCHE hébergé chez SESAMATH.

Il faudrait rajouter un bouton dans la partie "Gestion des utilisateurs" qui exporte en CSV le résultat de la recherche.

Pour cela il faudrait que l'admin panel génère du CSV à partir des résultats JSON.

**Comment by dlacroix** [comment]
Voici un projet qui peut donner des éléments:
https://eligrey.com/demos/FileSaver.js/

**Comment by HuguesGithub** [comment]
Poussé sur develop-hug

**Comment by dlacroix** [comment]
Ok c'est bon.
