### ISSUE TITLE
moteur de recherche d'utilsateurs à ajouter à un groupe libre

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#144]
"Bonjour,

Je souhaite créer des groupes libres dans le cadre de nos travaux internes en commission. Lors de la création d'un nouveau groupe, je m'aperçois que je ne suis pas présente dans la liste du menu déroulant pour administré le groupe. Poussant plus loi mes investigations, je me rends comptes que seuls les élèves semblent être présents dans la liste.

Il y a quelques semaines, j'avais créé 2 groupes libres, je me suis donc rendue sur l'un d'eux pour voir s'il m'était possible d'ajouter des personnes au groupe. Lorsque je sélectionne collège Bellecombe dans la partie droite n'apparaissent que les élèves et pas les personnels. Le chiffre annoncé de 500 utilisateurs ne correspondant d'ailleurs à rien.

Ci-joint une capture d'écran.

Nous souhaitions mettre en route des groupes libres pour travailler en interdegré (par la création d'utilisateurs pour le 1er degré) mais à l'heure actuelle, je suis totalement bloquée puisque je ne "trouve" même pas mes propres personnels.

C'est très très ennuyeux.

Cordialement,

-- 
Loubna Kerioui
Principale du Collège Bellecombe
10 rue de la Gaité 69006 LYON
tél : 04.78.52.94.48"
[problème groupe libre la classe.com.docx](https://github.com/laclasse-com/service-admin-panel/files/597546/probleme.groupe.libre.la.classe.com.docx)

**Comment by HuguesGithub** [comment]
Correctif livré.

L'API utilisée pour afficher le nom des utilisateurs était limitée à 500 éléments par défaut. Le filtre se faisait sur ces 500 noms et ne refaisait pas de requête.

La limite par défaut a été augmentée à 5000.
