### ISSUE TITLE
Changer le type d'une adresse email

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#145]
Dans le profil d'un utilisateur, si on édite l'adresse email et que l'on change son type. Une requête PUT part bien mais avant l'ancien type.

**Comment by HuguesGithub** [comment]
Correctif apporté. La variable du modèle n'était pas correctement nommée.
develop_hug mise à jour.

**Comment by dlacroix** [comment]
Je confirme c'est bon
