### ISSUE TITLE
Admin d'établissement  et ajout de profil

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#149]
Un admin d'établissement voit l'ensemble des établissements de laclasse.com lors de l'ajout d'un profil. C'est gênant.

**Comment by dlacroix** [comment]
Bon apparemment c'est une fonctionnalité pour permettre à un enseignant de s'auto déclarer dans un autre établissement. A ce moment là, il faudrait quand même réfléchir à cette fonctionnalité et peut être mettre une valeur par défaut sur l'établissement en cours.

**Comment by HuguesGithub** [comment]
Initialisation par défaut de la liste déroulante avec la valeur de l'établiseement courant.
