### ISSUE TITLE
Mettre la (ou l'une des...) matière enseignée de l'enseignant quand on le rattache à un groupe d'élèves

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#150]
Réponse intermédiaire : Quand on ajoute un enseignant à un groupe d'élèves en cliquant sur le +, afficher une pop up qui impose de choisir une matière

**Comment by HuguesGithub** [comment]
C'est maintenant le cas. Lors de l'ajout d'enseignant à un groupe d'élèves, il faut sélectionner la matière.
