### ISSUE TITLE
Laisser en gris la rubrique de l'admin panel sur laquelle on est

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#151]

**Comment by HuguesGithub** [comment]
Mis en place.
Pour les "sous écrans", on conserve la sélection précédente. A confirmer.
Par exemple, je suis sur la liste des Utilisateurs, je clique sur un Utilisateur en particulier, on garde la sélection sur "Gestion des Utilisateurs".
De même, on est sur l'interface "Groupes et Classes", on sélectionne une Classe puis un Utilisateur, on demeure sur la sélection "Gestion des Groupes et Classes".

**Comment by HuguesGithub** [comment]
Tag #1.3.22
