### ISSUE TITLE
Afficher les groupes libres dont on est admin en 1er sur la liste des groupes libres

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#152]
et proposer éventuellement en complément de trier dans un ordre et son inverse chaque colonne du tableau en cliquant sur son entête.

**Comment by HuguesGithub** [comment]
Afficher les groupes libres dont on est admin en premier sur la liste des groupes libres, Fait.

Next step : tri dynamique sur les autres colonnes.

**Comment by HuguesGithub** [comment]
J'ai mis en place le tri sur les colonnes "Groupe Libre" et "Nb membres".
Je conserve tout le temps les groupes dont on est admin en premier et à l'intérieur des deux ensembles, je trie selon "Groupe Libre" ou "Nb membres", ascendant ou descendant.

A pousser en dev/prod.

**Comment by heleroy** [comment]
Super, merci. Meilleurs voeux.
Hélène.


Le 2017-01-03 11:37, Hugues Joneaux a écrit :

**Comment by HuguesGithub** [comment]
Tag #1.3.22

**Comment by HuguesGithub** [comment]
Suite au refactoring des vues Groupes, cette fonctionnalité n'est plus en place.
En l'état, mis de côté et reporté sine die.
Toutefois, on peut "facilement" retrouver les groupes où l'on est Administrateur, d'une part via la petite pastille présente dans le cartouche "Administrateur" de la colonne "Composition", et d'autre part par la présence d'une case à cocher à la place d'un icône "Cadenas", dans la première colonne.

**Comment by HuguesGithub** [comment]
Mise en place d'une mécanique similaire aux Blogs.
Ajout d'une liste déroulante dans le header de l'interface pour pouvoir n'afficher que "Mes Groupes" par défaut. Et possibilité d'afficher "Tous les groupes" si l'utilisateur le souhaite.
