### ISSUE TITLE
dans "gestion des classes", afficher une alerte pour expliquer pourquoi on ne peut pas enregistrer sa nouvelle classe

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#156]
Lorsque l'on passe la souris sur le bouton "enregistrer" de la fenêtre qui permet de créer une classe, le pointeur se transforme en panneau "interdit". Expliquer pourquoi à l'utilisateur (par exemple parce qu'il a déjà créé cette classe et qu'il ne peut y avoir 2 classes au même nom).

**Comment by HuguesGithub** [comment]
Visiblement, l'unicité du nom du groupe n'est plus requise.
Le bouton est donc accessible.
