### ISSUE TITLE
Tri dans la gestion des groupes et des classes pour un chef d'établissement

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#158]
Dans les "Classes". Ce serait bien que par défaut il y ai un tri sur le "Nom".
Ce serait bien aussi que l'on affiche la colonne de tri.

Dans les "Groupes d'élèves", ce serait bien que l'on puisse trier. Sinon je ne vois pas pourquoi les colonnes "Nom" est "Description" sont en bleu.

Enfin pour les groupes libres. Il n'y a plus rien pour le tri...

**Comment by HuguesGithub** [comment]
Des mesures ont été prises sur les tris de ces différentes interfaces et qui devraient être livrées ce jour.
Récap à faire vis à vis de cette issue.

**Comment by HuguesGithub** [comment]
Initialisation :
-> Classes : tri sur le nom, statut TODO
-> Groupes d'élèves : tri sur le nom, statut TODO
-> Groupes libres : OK (En premier les groupes administrables par l'utilisateur, puis les autres. Dans chaque liste, tri par nom)

Fonctionnement :
-> Classes : Afficher la colonne de tri, statut TODO
-> Groupes d'élèves : Tri fonctionnel. Afficher la colonne de tri, statut TODO
-> Groupes libres : Tri foncitonnel. Afficher les colonnes pouvant être triées, statut TODO

**Comment by HuguesGithub** [comment]
Tag #1.3.22

**Comment by dlacroix** [comment]
Dans le détail de l'établissement pour l'ADM_TECH, dans "Groupes libres" (ex: CLG PR-CHARLES DE FOUCAULD sur v3dev), je comprends pas la tri alphabétique sur le nom. Il y a un problème. Pareil pour l'admin d'établissement.

**Comment by dlacroix** [comment]
ok
