### ISSUE TITLE
v4 - Affichage de l'id_sconet

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#162]
Pour un admin technique, dans la vue ENT \ Utilisateurs \ Profil afficher le champ id_sconet

**Comment by dlacroix** [comment]
Il ne s'affiche pas. Par exemple, en production pour l'utilisateur VCA66033. Rien alors que le champs aaf_struct_rattach_id et bien renseigné

**Comment by HuguesGithub** [comment]
Modification du champ affiché. Il ne s'appelle plus id_sconet... Donc forcément, ça n'affiche pas grand chose.
A pousser à l'occasion en prod.
