### ISSUE TITLE
Admin tech et édition des applications

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#164]
Dans "Toutes les applications", si je sélectionne une application et que je clic sur "EDITER". Je peux alors tout modifier y compris le champ "Code" qui correspond à l'Id. Lors que le valide c'est une requête POST d'ajout qui est exécuté. Si le champ "Code" a été modifié. Cela donne une nouvelle application. Bref rien a voir est une édition.

Interdire la modification du "Code". Faire une vraie requête PUT type /api/applications/MAIL

**Comment by HuguesGithub** [comment]
On ne peut plus modifié le code.
La requête envoie dorénavant un PUT et non plus un POST.
En attente du service côté Annuaire pour finaliser le traitement.

**Comment by HuguesGithub** [comment]
Suppression de la notion d'activation/désactivation.
(Rien à voir avec le problème initial, mais dans le même scope d'intervention et pas d'issue spécifique)
