### ISSUE TITLE
Affichage des classes, groupes... d'un établissement en ADM_TECH

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#165]
En ADMIN_TECH, si je viens juste de charger l'admin panel. Puis "Gestion des établissements", clic sur le premier établissement (ex: 069BACAS sur v3dev). Si clic sur l'onglet "Groupes libres", la tableau est vide même s'il y a normalement un contenu. C'est aussi valable pour les autres onglets sur ma version local semble t'il s'il s'agit de classes et groupes alimentés.

**Comment by HuguesGithub** [comment]
J'ai réussi à reproduire, mais ce n'est pas systématique. J'essaie de comprendre d'où ça vient.

**Comment by HuguesGithub** [comment]
A priori, si le premier établissement affiché comporte 0 Groupes d'élèves (0 classes poserait peut-être aussi le problème...), l'affichage ne fonctionne pas.

Si on revient en arrière et qu'on essaie de l'afficher, ça fonctionne. Si on essaie d'afficher un autre établissement avec 0 Groupes d'élèves, ça fonctionne aussi.

Lorsquon arrive sur l'écran détail, un Broadcast et envoyé aux 3 controllers qui gèrent les différents onglets pour actualiser les données. Il semblerait que dans notre cas qui plante, le broadcast n'est jamais reçu.

**Comment by heleroy** [comment]
je rajoute un comm ici pour ajouter le fait que l'admin tech ne peut faire aucune action sur ces affichages de groupes alors qu'en admin étab on peut : par exemple, cliquer sur le picto d'un utilisateur pour voir sa fiche.

**Comment by HuguesGithub** [comment]
Picto utilisateur pour accéder à sa fiche régler. Le problème venait du fait que le chemin d'accès à la page était en dur (/admin_etab/) et qu'il doit maintenant être variable depuis que c'est dans un environnement mixte.

**Comment by HuguesGithub** [comment]
Plus d'actualité, la présentation ayant changée.
