### ISSUE TITLE
Ajout d'une application pour un ADM_TECH. Impossible d'éditer le champ "code"

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#168]
Plus précisément, on peut taper une lettre (ou un copier/coller) puis le champ devient verrouillé.

Pas très pratique.

**Comment by HuguesGithub** [comment]
Effectivement.
La popup d'ajout et d'édition partagent le même code, et j'avais ajouté l'impossibilité de modifier le code pour une édition, s'il était renseigné. Et forcément, ça a impacté sur l'ajout.

Code modifié pour traiter spécifiquement chaque cas.
