### ISSUE TITLE
tri

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#17]
permettre de trier les tableaux

**Comment by HuguesGithub** [comment]
Sur certains tableaux, le tri est prévu.
Par exemple sur l'écran "Gestion des utilisateurs", il est possible de trier sur le prénom ou le nom. Mais un problème de css empêche de voir cette fonctionnalité. Par défaut, la classe de l'icone permettant le tri est à "icon-sort" puis à "icon-caret-down" et "icon-caret-up". Ces classes n'existent pas.

Ceci étant dit, il est possible de passer par angular qui devrait gérer ça de cette façon :
<table class="table">
	<tr>
		<th><a href="" ng-click="orderByField='name'; reverseSort = !reverseSort">Name</a>
		</th>
		<th><a href="" ng-click="orderByField='employees'; reverseSort = !reverseSort">Employees</a>
		</th>
		<th><a href="" ng-click="orderByField='headoffice'; reverseSort = !reverseSort">Head Office</a>
		</th>
	</tr>
	<tr ng-repeat="company in companies  | filter: searchKeyword | orderBy:orderByField:reverseSort">
		<td>
		</td>.....

**Comment by HuguesGithub** [comment]
Liste des pages susceptibles d'accueillir une fonctionnalité de tri et de filtre :
- [ ] Utilisateurs > Gestion des utilisateurs
- [ ] Etablissements > Gestion des établissements
- [ ] Etablissements > Matières enseignées
- [ ] Applications > Toutes les applications
- [ ] Droits > Gestion des rôles
- [ ] Ressources > Ressources numériques
- [ ] Groupes > Gestion des groupes et classes

**Comment by HuguesGithub** [comment]
Le tri proposé ci-dessus ne trie que la pagination courante.
Reste à trouver l'option qui permet de trier sur toutes les données, sinon, il faudra trouver une autre solution.

**Comment by HuguesGithub** [comment]
Le tri parcourt l'ensemble des résultats.
Cette fonctionnalité sera présente dans le prochain merge vers develop.
