### ISSUE TITLE
problème d'affichage avec filtrage des groupes d'élèves activé sur la liste des utilisateurs

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#170]
![capture du 2017-05-09 10-05-05](https://cloud.githubusercontent.com/assets/7963908/25841335/f9f15408-349f-11e7-8f6f-357d4439b87f.png)
C'est le libellé AAF qui apparaît dans les résultats alors que c'est le nom modifié du groupe qui apparaît sur le filtrage. L'idéal ce serait que ce soit le nom modifié qui apparaisse partout car si le nom a été modifié, c'est qu'il n'était pas très "parlant" même s'il répond aux recommandations académiques. 
Après, je comprends que le libellé AAF soit pratique pour la taille de la colonne car limité à 8 caractères ;)

**Comment by HuguesGithub** [comment]
Disponible en prod.
