### ISSUE TITLE
v4 - Lors de l'ajout d'un profil sur la page détail d'un utilisateur

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#184]
Si l'utilisateur n'a aucun profil, si on en ajoute 1 on se retrouve avec 2 fois le profil affiché. (problème que l'on n'a plus si on recharge la page)

**Comment by HuguesGithub** [comment]
Pas systématique.
Si on supprime tous les profils d'un utilisateur, puis on rafraichit l'écran et qu'on ajoute un profil, il n'y a qu'une seule ligne.
Si on supprime le profil, puis qu'on en créé un nouveau (sans rafraîchir l'écran), on a deux lignes.

**Comment by HuguesGithub** [comment]
Le problème vient du fait que le Delete ne met pas à jour le contenu Angular de profiles du User affiché. Quand on en créé un nouveau, il l'ajoute dans Angular et affiche le contenu de profiles, dont l'ancien profil.

**Comment by HuguesGithub** [comment]
Le problème était un peu plus complexe. Ca n'était pas qu'un problème de profils dans l'établissement, mais aussi un problème de liste d'établissements utilisée pour l'affichage groupé.
