### ISSUE TITLE
v4 - Suppression multiple de regroupements et boîte de confirmation

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#185]
Si on sélectionne 50 regroupements à supprimer, que l'on clic sur "SUPPRIMER", la boîte de dialogue de confirmation apparaît. Le problème c'est qu'elle affiche le 50 regroupements et pas un extrait des premiers avec ...

**Comment by HuguesGithub** [comment]
Corrigé.
Les 5 premiers sont listés et le nombre restant est affiché.
