### ISSUE TITLE
v4 - BUG édition d'une classe, les niveaux ne sont pas affichés

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#188]
Dans la "gestion des regroupements", si j'édite une classe, dans la popup j'ai un liste déroulante pour le niveau. Ce champs et vide (alors qu'il y a bien des niveaux) et ne correspond pas au fait que la classe a plusieurs niveaux.

**Comment by HuguesGithub** [comment]
Suite à l'évolution de la fonctionnalité (passage de mono-valué à multi-valué), l'interface n'a pas encore été mise à jour. Pour le moment, cette information a été retirée de l'interface.
