### ISSUE TITLE
Annuler la modification du numéro de téléphone

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#191]
En cliquant sur le bouton annulation, les modifications sont quand même prises en compte et affichées dans le panneau "information générales"

**Comment by HuguesGithub** [comment]
Problème idetifié.
Les modifications apportées dans la popup sont conservées dans l'objet Angular malgré l'annulation de la demande.
Les données ne sont pas modifiées en base et un refresh de l'interface corrige la modification erronée.
Correctifs à venir, annuler les modifications qui ont été effectuées dans la popup, avant de la fermer.

**Comment by HuguesGithub** [comment]
Existant aussi sur la modification d'un Regroupement. Correctif appliqué également.
