### ISSUE TITLE
v4 - l'ajout d'un nouveau groupe libre ne fonctionne plus

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#193]
Même pour les profils administrateurs d'établissement, la création à partir du bouton ajouter affiche l'erreur "une erreur est survenue endant la tentative de création. Veuillez essayer à nouveau."

**Comment by HuguesGithub** [comment]
Non reproduit en local. Toutefois, on remarque une requête de Users assez longue qui peut avoir posé problème lors du test.
C'est un reliquat de ce qui se faisait avant sur cette interface, le front avait été enlevé, mais visiblement, pas tout le backend.
Correctif apporté, à délivrer dès que possible.
