### ISSUE TITLE
v4 - Edition des applications le mot de passe n'est pas affiché

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#195]
Le champ "Clé de l'application" et toujours vide alors que cette valeur est disponible.

**Comment by HuguesGithub** [comment]
Sur la Prod, Admin et Annuaire ont bien leur champ renseigné.
Trombi n'a effectivement pas de donnée, mais aucune donnée n'est présente dans l'objet renvoyé.
