### ISSUE TITLE
v4 - Ajout d'un regroupement

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#196]
Lorsqu'un super admin (pas testé avec les autres) veut ajouter un regroupement, l'ouverture de la boîte de dialogue déclenche la requête suivante: /api/users?sort_col=lastname&sort_dir=asc

Soit le chargement de l'intégralité des comptes utilisateurs de l'ENT. A corriger.

**Comment by HuguesGithub** [comment]
C'est un reliquat foireux de l'ancienne popup. La recherche n'était censé se lancer que lorsqu'un établissement était sélectionné.
Mais ce n'est plus le cas pour le moment. L'appel a ce code a été supprimé et la modification mise à disposition sur develop_hug hier soir : https://github.com/laclasse-com/service-admin-panel/commit/bfbfc96c25a09d33c106e3e3cf13100fd648f25e
