### ISSUE TITLE
La pagination ne fonctionne pas sur la liste des membres d'un groupe d'élèves.

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#198]
la pagination, recherche et modification du nb de résultats par page ne fonctionne pas.

**Comment by HuguesGithub** [comment]
La valeur "limit" ne semble pas être modifiée même lorsqu'elle est changée dans l'interface. On n'a donc pas de nouvelle requête envoyée pour récupérer les données correspondantes.

Il doit y avoir exactement la même problématique au niveau de la pagination et de la recherche.
Par contre, je ne comprends pas pourquoi pour le moment.

**Comment by HuguesGithub** [comment]
L'ensemble de ces éléments se trouvaient dans un bloc conditionnel. Selon les droits de l'utilisateur, il était affiché ou non.
Ce bloc conditionnel était géré via un ng-if qui créé un nouveau scope. De fait, son contenu (dont les 3 variables en question) n'est plus dépendant du controller attendu.
Problème réglé. Merci Daniel.

**Comment by CharlotteRizzo** [comment]
Les nouveaux tests du jour montrent que ça ne fonctionne toujours pas.  
![Uploading p2.PNG…]()
![Uploading p1.PNG…]()

**Comment by HuguesGithub** [comment]
Bonjour.

Les développements poussés sur develop vendredi dernier ont bien été installés dans l'environnement où tu testes, hein ?

-----Message d'origine-----
De : "CharlotteRizzo" <notifications@github.com>
Envoyé : ‎21/‎08/‎2017 18:12
À : "laclasse-com/service-admin-panel" <service-admin-panel@noreply.github.com>
Cc : "Hugues Joneaux" <jhugues@jhugues.fr>; "Assign" <assign@noreply.github.com>
Objet : Re: [laclasse-com/service-admin-panel] La pagination ne fonctionne pas sur la liste des membres d'un groupe d'élèves. (#198)

Les nouveaux tests du jour montrent que ça ne fonctionne toujours pas.
