### ISSUE TITLE
V4- création de groupes impossible pour les enseignants

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#205]
Avec un profil enseignant, il est uniquement possible de visualiser les groupes. 
Est -il possible d'ajouter un bouton de création de nouveau groupe libre ? et ainsi d'accéder à la page de création et de modification du groupe libre créé ?

**Comment by HuguesGithub** [comment]
Pris en compte et mis en place.
Toutefois, il semblerait qu'un enseignant n'ait pas les droits de faire une telle action.
Issue ouverte sur LaClasseServices.
