### ISSUE TITLE
V4 - la page "statistiques" pour les enseignants est blanche

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#206]
Ne pas laisser de vide, soit : 
- laisser l'onglet statistique, ne pas rediriger vers la page statistique lorsqu'on clique et afficher un message directement dans la page de l'admin panel : "votre profil ne permet pas d'accéder à cette option"

- laisser l'onglet statistique, rediriger vers la page et ajouter un message d'erreur dans la page qui s'ouvre + ajouter un bouton de redirection vers la page précédente

- enlever l'onglet statistique pour les profils enseignants

**Comment by HuguesGithub** [comment]
Lien retiré pour un profil non Admin.
