### ISSUE TITLE
V4 - Gestion des groupes via l'onglet mon profil

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#211]
Penser la gestion des groupes dans l'onglet mon profil dans le même sens que l'onglet des groupes : 

- permettre de faire une demande pour rejoindre un groupe libre existant ou un groupe de son établissement 
- voir apparaitre une icône "en attente de validation"
- synchroniser les informations avec l'onglet Groupes 

- permettre de supprimer les groupes qui ont été rejoints précédemment (mais pas ceux dont on est administrateur)

**Comment by HuguesGithub** [comment]
Différents points mis en place.
Poussé ce jour sur develop.

**Comment by HuguesGithub** [comment]
En l'état, ne peut pas faire de demande pour rejoindre un Groupe d'élèves rattaché à l'établissement et non alimenté.
Est-ce normal ?
