### ISSUE TITLE
v4- import csv fichier enseignant ne fonctionne pas

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#218]
![import non fonctionnel](https://user-images.githubusercontent.com/24314392/29216284-7b85b0d8-7eae-11e7-96ba-3ce6d48e7eeb.PNG)

Civilité | Nom | Prénom | Mail académique
-- | -- | -- | --
Monsieur | TestAout1 | TEst1 | test@test.fr
Monsieur | TestAout2 | TEst2 | test@test.fr
Monsieur | TestAout3 | TEst3 | test@test.fr
Monsieur | TestAout4 | TEst4 | test@test.fr
Monsieur | TestAout5 | TEst5 | test@test.fr

**Comment by CharlotteRizzo** [comment]
+ les lignes 1 et 2 ne sont pas prises en compte

**Comment by HuguesGithub** [comment]
Les lignes ne sont pas prises en compte car le mail académique existe et les Nom & Prénoms ne correspondent pas.
Corriger et mettre en place la gestion des conflits.

**Comment by HuguesGithub** [comment]
Mis en prod.
