### ISSUE TITLE
V4- import CSV préciser les problèmes de formats de données dans le fichier source

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#219]
Import d'une base Elèves
Lorsque les types champs de données sont mal renseignés pour :
- la date de naissance (nombre)
- le code postal (nombre)
- le sexe (M ou F)
Les comptes ne se créent pas.
> Créer un message d'erreur pour savoir d'où vient le problème et sur quel compte. 
> Créer et mettre à disposition dans la fenêtre de création de l'import un template de tableau CSV avec les bons formats en exemple:
Nom Elève;;Prénom Elève;Date naissance;Sexe;Adresse1;Cp1;Commune1;;;;;;;Niveau;Classe
XX;;XX;00/00/2000;M;XX;00000;XX;;;;;;;XX;XX

**Comment by HuguesGithub** [comment]
Mis en prod.
