### ISSUE TITLE
V4-import CSV la liste affichée n'est pas dans le même ordre que celle du fichier

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#221]
Cela ne pose pas de problème majeur, mais c'est un peu étonnant. Pour un fichier prof, les données analysées ne sont pas affichées dans l'ordre.
![affichage des analyses](https://user-images.githubusercontent.com/24314392/29526408-ece496e2-8695-11e7-90f5-a207f6c03d64.PNG)
![fichiercsv](https://user-images.githubusercontent.com/24314392/29526411-ed9aad42-8695-11e7-9b45-3c5951504118.PNG)

**Comment by HuguesGithub** [comment]
Explication du pourquoi du comment :
Le traitement analyse le fichier ligne par ligne. A chaque ligne, il envoie une requête au serveur pour obtenir les informations stockées en base, relatives à la ligne. Le serveur peut prendre plus ou moins de temps pour faire ce traitement et il est possible qu'une demande ultérieure ait sa réponse retournée avant une demande antérieure. Exemple : Demande des lignes A, B, C, D; réponse du serveur : A, D, B, C.
L'affichage de l'analyse s'appuie sur l'ordre de retour du serveur.

Quelles solutions proposer ?
 - Ne faire une demande pour la ligne N+1 que lorsque la réponse du serveur pour la ligne N est revenue. Inconvénient : Traitement plus long.
 - Tagguer chaque requête envoyée au serveur avec un compteur incrémental. Une fois que toutes les réponses sont venues, appliquer un tri croissant sur ce compteur.
 - Appliquer un tri par défaut sur le Nom de l'utilisateur (puisque probablement celui qui existera dans le fichier soumis) et permettre l'application de tri sur les autres colonnes.

On part sur la troisième solution.

**Comment by HuguesGithub** [comment]
Tri sur le nom en place.
