### ISSUE TITLE
V4 - Améliorer la liste des regroupements sur la vue d'un profil utilisateur

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#222]
![capture du 2017-08-22 08-52-45](https://user-images.githubusercontent.com/7963908/29552398-6ae3601a-8717-11e7-889f-b39f9990fa46.png)

Je ne sais pas comment sont listés les rattachements aux regroupements... Ça semble un peu tout mélangé et on n'identifie pas en un coup d’œil les groupes de tel établissement et les groupes de tel autre établissement. Idem, on différencie mal les différents groupes. Le code couleur est peut-être  à revoir ? et la présentation plutôt par établissement puis par type de regroupement ?
 cf capture pour un compte rattaché à 2 établissements. De plus les codes couleurs semblent inversés par rapport à ce qui existe sur le CT (vert et bleu par exemple).

**Comment by HuguesGithub** [comment]
Réflexion sur les codes couleur en cours.

**Comment by HuguesGithub** [comment]
Création de classes "label" spécifiques à nos besoins, en reprenant les codes couleurs des classes "label" de bootstrap.

Deuxième partie : Essayer d'améliorer le visuel de la présentation des groupes d'un utilisateur.

**Comment by HuguesGithub** [comment]
Proposition visuel :
![evol-groups-detail-user.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ebd019cd25fd1300ef78a2/125516c66e82c728ace21e0d46ed82952fcf84bb80fcaf50e959f580284f2b3e3c17a63932c9a138ad4d71040c1b5ca6535d5b4cfaaf8d2af4b33a758c0f5dedd36d5f27cf3418aaee9003ad43eb7edf10d8eff6df0ed2e22f24ef818e4a3f1f04108afa5b32a19d4dda15.png)
