### ISSUE TITLE
Un enseignant peut s'ajouter à une classe via son profil mais l'admin ne peut le valider

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#230]
Est-ce normal qu'un enseignant puisse faire une demande d'ajout à une classe depuis son profil ? et si oui, il faudrait alors mettre le bouton "+ ajouter" aussi au bas du tableau des groupes et corriger le fait que ça bug quand l'admin valide la demande (cf capture).
Et si ce n'est pas souhaitable, alors il faut penser à supprimer le bouton "ajouter" sur son propre profil quand on est prof et supprimer le processus de demande de validation et de validation de la demande par l'admin.
J'imagine que ça doit etre pareil pour les groupes d'élèves.
![capture du 2017-09-04 10-38-54](https://user-images.githubusercontent.com/7963908/30019491-0d140db4-9161-11e7-858d-3d7fce36064a.png)

**Comment by HuguesGithub** [comment]
J'ai pu valider en tant qu'Admin, et je ne vois pas d'erreur sur la capture écran.
Pour ce qui est de la question de fond, l'enseignant a-t-il le droit de faire une demande, on en discute de vive voix.

Et oui, c'est la même mécanique pour les Groupes d'élèves.

**Comment by HuguesGithub** [comment]
Un Enseignant n epeut plus s'inscrire à une Classe ou un Groupe d'élèves, seulement à un Groupe Libre.
