### ISSUE TITLE
Afficher par défaut la liste des groupes dans un certain ordre (plutôt classe d'abord, puis groupes d'élèves et enfin groupes libres)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#231]
Sur la page de la gestion des groupes. (Je ne parle pas de la liste déroulante, qui elle, est dans un ordre logique).
![capture du 2017-09-04 10-20-02](https://user-images.githubusercontent.com/7963908/30019582-642e6ce8-9161-11e7-85c6-939494a536f1.png)

**Comment by HuguesGithub** [comment]
Le tri par défaut est sur le nom du groupe.
Dés lors qu'un tri sera fait, il ne sera pas possible de refaire untri sur les Types. Est-ce vraiment pertinent de proposer un état vers lequel on ne pourra pas revenir à moins de rafraîchir toutes les données ?
Le tri peut artificiellement être fait en sélectionnant un Type de groupe.

Ceci étant dit, les donées de ce champ sont : 
 - CLS : pour Classe
 - GPL : pour Groupe Libre
 - GRP : pour Groupe d'élèves
Ce sera donc l'ordre par défaut sur un tri simple.
Un autre tri est possible, mais ça demande un peu plus de traitement.

A confirmer.

**Comment by HuguesGithub** [comment]
Après analyse :
 - Les données affichées sont partielles (à moins que le nombre d'entrées soit inférieur à la limite affichée par page), le tri ne peut donc pas être fait sur l'interface. Il doit être fait au niveau de la requête SQL.
 - L'ordre de tri souhaité n'est pas pratique, puisque les labels utilisés sont "CLS"-"GRP"-"GPL".
 - En admettant qu'un tri par Type puisse être mis en place, on a le nom des groupes complètement en désordre. Naturellement l'utilisateur aura tendance à trier sur les noms pour s'y retrouver et éventuellement à filtrer par le Type. On perdra la présentation initiale.
 - On peut envisager un tri simultané sur plusieurs colonnes. Mais ça demande de bien penser l'interface.

En conclusion, en l'état, requête mise de côté.
