### ISSUE TITLE
l'ajout d'image de bannière d'éts ne fonctionne pas (rubrique "informations")

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#24]
testé depuis un profil "direction" le 21/05

**Comment by HuguesGithub** [comment]
La console Firebug remonte une erreur JavaScript. Celle-ci bloque peut-être l'exécution de la fonction javascript "submit()" placée sur le bouton "Ajouter".

**Comment by HuguesGithub** [comment]
Le message d'erreur de la console Firebug semble indiquer une insertion multiple de la même directive. En supprimant l'attribut "markers" de la div "google-maps", l'erreur disparait de la console Firebug.

**Comment by HuguesGithub** [comment]
J'ai supprimé l'attribut "markers". Je n'ai plus l'erreur indiquant l'insertion multiple.
Les diverses données s'affichent correctement, à l'exception de la map. L'image par défaut ne semble pas fonctionner (https://v3dev.laclasse.com/api/logos/null).

De plus, l'upload de la bannière ne fonctionne toujours pas.
 - url accédée : https://v3dev.laclasse.com/api/etablissements/0691481K/upload/logo
 - erreur retournée : "NetworkError: 500 Internal Server Error - https://v3dev.laclasse.com/api/etablissements/0691481K/upload/logo"
(l'id établissement est bien celui indiqué dans l'entête de la barre latérale gauche (CLG-LAURENT MOURGUET: 0691481K)

**Comment by HuguesGithub** [comment]
Ajout du répertoire "logos" à la racine de l'api pour stocker la bannière de l'établissement. L'upload fonctionne correctement.
