### ISSUE TITLE
v4 - Dans le détail d'un blog, dans la liste des utilisateurs des blogs, bugs dans l'édition

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#242]
Depuis la mise en place de l'édition, je note 2 bugs:
- si on sélection plusieurs éléments, que l'on édite pour changer le rôle, après avoir validé, la liste ne se met pas à jour (le rôle)
- si on édite 1 seul élément, l'API est quand même utilisé avec un tableau en envoi pour modification, du coup la réponse est un tableau. Problème Angular plante car il n'attends qu'un objet

**Comment by HuguesGithub** [comment]
Poussé sur develop-hug.
