### ISSUE TITLE
Affichage peu lisible gestion des blogs

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#243]
L'étiquette n'apparait pas bien : 

![capture blog](https://user-images.githubusercontent.com/24314392/32651827-8971b99e-c602-11e7-8b8c-2d105ad36f99.PNG)

**Comment by HuguesGithub** [comment]
Si l'id du Groupe est indéfini, on n'a pas de lien.
Si l'id du Groupe est renseigné et que le groupe existe, on a un lien.
Si l'id du Groupe est renseigné, mais que le groupe n'existe plus, on ne devrait pas avoir de lien.
Corrigé, à pousser en prod.
