### ISSUE TITLE
(Amélioration) voir le nom de l’administrateur lorsqu’on a fait une demande d’accès à un groupe libre

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-admin-panel#244]
si la demande n'a pas été acceptée depuis longtemps, cela permet de directement contacter l'administrateur

**Comment by HuguesGithub** [comment]
Je propose, que lorsqu'un utilisateur consulte un groupe dont il n'est pas membre ou en attente de validation, soit uniquement affichée la liste des Administrateurs du groupe.

Ça donnerait quelque chose comme ça  (avec l'entête du tableau en plus) :

![Capture du 2017-12-07 11-24-07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ebd019cd25fd1300ef78a2/125516c66e82c728ace21e0d46cb958a379791accfedaa03f60da1c36417753e7953e37a21c8b17cf2122c43434d0eee1e020a17b8eb8339a3b23476dc580abfd46b5a72956b11aeb8824cb608b326dd5d99a4fedb1294b7607caddecd5d340c041f83fe5834a29f4fca5afe4ee04e51b65e.png)

**Comment by heleroy** [comment]
Du coup, avec cette proposition de Hugues de ne voir que les admins du groupe, ça ne permets pas de savoir si un groupe a beaucoup d'utilisateurs ou pas.

**Comment by CharlotteRizzo** [comment]
Le but de cette demande est de pouvoir contacter l'administrateur lorsqu'on veut rejoindre le groupe. Toute la liste n'est peut être pas utile ?

**Comment by HuguesGithub** [comment]
@heleroy : Avant, on ne voyait rien sur le détail du groupe, il n'y avait 0 informations.

Par ailleurs, on a la composition du groupe dans le listing des Groupes.
On connaît le nombre de Membres / Admin d'un Groupe Libre, ou le nombre d'Élèves / Enseignants / Prof principaux d'une Classe ou d'un Groupe d'Élèves.
