### ISSUE TITLE
Erreur à la création d'un groupe hors établissement

### ISSUE THREAD

**Issue by n-goncalves** [laclasse-com/service-admin-panel#248]
structure_id doit correspondre à un établissement valide ou la valeur `null` or lorsque "Hors Etablissement" est sélectionné, le request payload de la requête de création de groupe contient un structure_id `"NULL"`

exemple : 
```json
{
  "name": "GROUPE HORS ETAB",
  "structure_id": "NULL", 
  "type": "GPL",
  "users" :[
    {
      "user_id": "XXXXXXX", 
      "type": "ADM"
    }
  ]
}
```
A corriger en enlevant l'option "Hors Etablissement"  des options ou alors en passant `null` lorsque cette option est sélectionnée, a voir.

**Comment by dlacroix** [comment]
Fait
