### ISSUE TITLE
Créer un bouton "plein écran" sur l'interface d'administration dans les rubriques où on visualise une fenêtre dans la page pour pouvoir l'ouvrir en pleine page (par exemple la gestion des utilisateurs de l'établissement car sinon on ne voit pas facilement que l'on a des boutons d'actions sur la droite)

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#31]

**Comment by HuguesGithub** [comment]
Plutot que de prévoir un full "plein écran", pourrait-on envisager au niveau du titre de la sidebar un bouton (<<) qui réduirait la largeur du menu latéral et augmenterai la largeur du conteneur principal. Ils passeraient ainsi respectivement de span3 et span9 à span1 et span11. 

Avantage : Le menu reste accessible, même si un peu moins pratique.
Inconvénient : Certains libellés longs peuvent être tronqués.

Si l'esprit "plein écran" est conservé, on peut cacher le menu latéral et mettre un span12 au conteneur principal.

**Comment by HuguesGithub** [comment]
Après réflexion, cette piste est abandonnée. Il lui est préféré une modification de l'interface, en supprimant la colonne contenant ces boutons d'actions et en ajoutant des boutons d'actions équivalents en pied de tableau. Confère #54
