### ISSUE TITLE
Pour la création de groupes libres sur l'interface d'administration, il n'est pas possible d'ajouter des personnes en dehors de son établissement or le but de ces groupes (contrairement aux classes et groupes d'élèves) est de pouvoir travailler entre plusieurs établissements

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#32]

**Comment by HuguesGithub** [comment]
Pourrait-on envisager un fonctionnement comme l'illustre la capture écran ?
Par défaut un onglet de l'établissement de rattachement du profil en cours. Une liste déroulante de tous les autres établissements rattachés aux différents profils (doit-on d'ailleurs limiter à ces établissements, ou doivent-ils tous être disponibles ?), sur la sélection d'un de ces établissements, il remplace l'établissement "courant" et les données relatives à celui-ci sont chargées.

![maquette](https://www.dropbox.com/s/u4gut88g89a734b/waffle-32.png?dl=1)

**Comment by cycojesus** [comment]
On pourrait n'avoir que la liste déroulante, sans l'onglet. Il serait bien d'afficher à quel établissement appartient une personne attachée au groupe.

**Comment by HuguesGithub** [comment]
L'établissement sélectionné serait en lieu et place de "Autre" et on aurait par défaut l'établissement courant ?
Par contre, si on n'affiche que les utilisateurs de l'établissement sélectioné, c'est pas forcément pertinent d'indiquer l'établissement de rattachement d'une personne, à cet endroit.
Ceci étant dit, dans la liste des utilisateurs du groupe libre, ça pourrait sans doute être pertinent.

**Comment by cycojesus** [comment]
1. oui,
2. oui, dans la liste des utilisateurs sélectionnés.

**Comment by HuguesGithub** [comment]
Suite à quelques échanges oraux, on a décidé de ne pas mettre les informations relatives à l'établissement et au statut de l'utilisateur ajouté au groupe.

La fonctionnalité d'ajout depuis différents établissements a été mise en place.
D'importantes logs d'erreur étaient présentes dans la console de log, le code a été corrigé pour les éviter.

Il reste un bug à corriger. Lors de l'affichage d'un établissement, si on parcourt la pagination jusqu'à la page 11 par exemple, puis que l'on utilise la fonctionnalité de filtre, on peut se retrouver avec un nombre de page inférieur à la page courante.

**Comment by HuguesGithub** [comment]
Dernier bug corrigé. Cette fonctionnalité sera jointe dans le prochain merge vers develop.
