### ISSUE TITLE
Sur l'interface d'administration, sur la gestion des utilisateurs, la liste des utilisateurs est dans un certain ordre (mais lequel ?), serait-il possible de les classes par ordre de profil, puis ordre alphabétique pour que ce soit un peu plus logique à première vue

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#33]

**Comment by HuguesGithub** [comment]
plus permettre à l'utilisateur de trier manuellement

**Comment by HuguesGithub** [comment]
Après étude, il est possible de trier selon le nom et le prénom. Le lien n'est "juste" pas visible.

**Comment by HuguesGithub** [comment]
Le tri par défaut se fait sur l'id croissant de l'utilisateur.

**Comment by HuguesGithub** [comment]
Un tri similaire à celui sur la colonne Nom ou Prénom a été mis en place. Cependant, il ne fonctionne pas, une erreur est rencontrée. ("Une erreur s'est produite : Colonne de tri profils non acceptée ").

**Comment by HuguesGithub** [comment]
Suite à l'ajout du filtre Profils, plus vraiment nécessaire.
