### ISSUE TITLE
Sur l'interface d'administration, sur la liste des groupes libres, serait-il possible de mettre en avant les groupes libres créés par des personnes de l'établissement ?

### ISSUE THREAD

**Issue by gwenhael-le-moine** [laclasse-com/service-admin-panel#34]

**Comment by HuguesGithub** [comment]
L'information n'est pas présente, ni dans le scope, ni dans la base.
Création d'une issue [#78](https://waffle.io/laclasse-com/service-annuaire) dans service-annuaire afin de créer le champ en question.

Une fois fait, on pourra envisager de récupérer l'information et la traiter.

**Comment by TestsCGI** [comment]
Issue mère : #159

**Comment by TestsCGI** [comment]
Détail de l'enrichissement des données à faire sur la liste des groupes libres :
- ajout des données suivantes 
(1) Nom de l'administrateur du groupe libre, affiché dans une nouvelle colonne
(2) Si possible nom de l'établissement de l'administrateur du groupe libre, affiché dans une nouvelle colonne
(3) Bulle avec le nombre de demandes d'inscription faites par les utilisateurs pour les groupes libres privés, et à traiter par l'administrateur de l'établissement, affichée dans la colonne nombre de membres du groupe
(4)  Statut indiquant 
- le rôle de l'utilisateur connecté par rapport à chacun des groupes libres privés ou publics : membre ou administrateur
- le traitement d'une demande d'inscription à un groupe libre privé par l'utilisateur demandeur : en attente / refusée. Tant qu'une demande n'est pas traitée par l'administrateur, c'est le statut "en attente" qui est affiché. Une demande d'inscription validée entraîne le changement de rôle de l'utilisateur pour ce groupe : il devient "membre". Lorsqu'une demande est refusée par l'administrateur, alors c'est le statut "refusée" qui reste affichée pour l'utilisateur demandeur
(5) Une icône de type clé ou cadenas signalant devant leur nom les groupes libres privés

- affichage en vert et en-tête de la liste des groupes libres les groupes libres de(s) l'établissement(s) de l'utilisateur connecté

**Comment by HuguesGithub** [comment]
Refonte de la mécanique des Groupes Libres. Le principe de groupe publics/privés n'est pas retenu.
Les points 1 et 2 ne sont pas mis en place.
Le point 3 l'est.
Le point 4a n'est pas pris en compte, le 4b l'est.
Le point 5 a été légèrement détourné, on affiche un cadenas au lieu de la checkbox sur les groupes où l'utilisateur n'a pas de droits d'administration.
Point en gras, non mis en place, un filtre pouvant être fait.
