### ISSUE TITLE
deconnection sur ipad safari

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-admin-panel#39]
Lorsque que l'on se connecte avec un utilisateur jmoulin et que l'on se deconnecte pour utiliser un autre utilisateur erasme on reste sur la page admin pan mais avec l'affichage de l'ancien compte que l'on avait utiliser en premier sur le bandeau laclasse en haut c'est a dire sur le compte de joel. c'est un peu déroutant et il faut donc raffraichir

**Comment by TestsCGI** [comment]
non reproduit sur acer chrome
