### ISSUE TITLE
Création de groupes libres pour les profs

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-admin-panel#42]
Rendre possible la création de ces groupes pour les profs. Les formulaires existent mais ne sont disponibles que pour les administrateurs d'établissement.
Il ne s'agit peut-tre que d'une histoire de droits d'accès, mais cela reste à étudier.

**Comment by HuguesGithub** [comment]
Que ce soit en environnement de dév ou de prod, la fonctionnalité est présente en tant qu'enseignant. A vérifier qu'on parle bien de la même chose.
