### ISSUE TITLE
Ergonomie et ménage

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#54]
- [ ] enlever l'affichage de l'heure
- [ ] enlever le copyright
- [ ] Gestion des utilisateurs
    - [ ] enlever les boutons d'actions
    - [ ] sortir les actions multiples en boutons individuels dans le footer du tableau
    - [ ] différencier visuellement les utilisateurs "alimentés" de ceux crées manuellement (id_jointure_aaf == null dans ce dernier cas)

**Comment by HuguesGithub** [comment]
- [ ] enlever l'affichage de l'heure
- [ ] enlever le copyright
- [ ] Gestion des utilisateurs
    - [x] enlever les boutons d'actions
    - [x] sortir les actions multiples en boutons individuels dans le footer du tableau
    - [ ] différencier visuellement les utilisateurs "alimentés" de ceux crées manuellement (id_jointure_aaf == null dans ce dernier cas)
- [ ] Passer à Bootstrap 3.3.6 ....

J'ai par ailleurs modifié le "check_all". Plutôt qu'une case à cocher, je l'ai rempalcé par une icône et j'ai rapatrié au même niveau le bouton de déselection.

**Comment by HuguesGithub** [comment]
Affichage de l'heure et copyright enlevés.

**Comment by HuguesGithub** [comment]
- [x] enlever l'affichage de l'heure
- [x] enlever le copyright
- [x] Gestion des utilisateurs
    - [x] enlever les boutons d'actions
    - [x] sortir les actions multiples en boutons individuels dans le footer du tableau
    - [x] différencier visuellement les utilisateurs "alimentés" de ceux crées manuellement (id_jointure_aaf == null dans ce dernier cas)
- [ ] Passer à Bootstrap 3.3.6 ....

Pour différencier les utilisateurs alimentés vs manuels, j'ai colorié d'un fond verdâtre (class="success") le tr de l'utilisateur concerné.

Pour la migration à Bootstrap 3.3.6, on a une doc qui permet d'avoir un coup de main à cette [url](http://www.bootply.com/bootstrap-3-migration-guide)
