### ISSUE TITLE
Est-il légitime qu'un admin d'établissement puisse supprimer un utilisateur ?

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#55]
- oui pour ceux qui ont été créés manuellement dans son établissement,
- non pour les utilisateurs alimentés,
- non pour les utilisateurs aussi attachés à d'autres établissements.

**Comment by HuguesGithub** [comment]
Pas mieux.

Aussi, le bouton supprimé doit-il être accessible uniquement si l'ensemble des utilisateurs sélectionnés répondent au premier critère uniquement ?
Ou l'est-il tout le temps et un contrôle se fait au moment de l'action pour prévenir que ça n'est pas possible ?
