### ISSUE TITLE
Gestion des adresses email

### ISSUE THREAD

**Issue by gwenhael-le-moine** [laclasse-com/service-admin-panel#59]
- [ ] interdire la saisie d'une adresse déjà attribuée
- [x] interdire la modification de l'adresse VAAxxxx@...

**Comment by HuguesGithub** [comment]
Ajout contrôle unicité du mail sur l'inscription d'un utilisateur (interface users), ainsi que sur le profil d'un utilisateur sur l'ajout et l'édition des mails.

**Comment by HuguesGithub** [comment]
Tag #1.3.22
