### ISSUE TITLE
Scrollbar horizontale toujours présente

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-admin-panel#60]
Le "container" (la classe .container id panel-content) a une taille de 98% + les margin-right: auto; et
margin-left: auto; font que la scrollbar horizontale est toujours affichée. C'est anormal et énervant.

**Comment by HuguesGithub** [comment]
La problématique ne survenait pas tout le temps mais dès que la largeur d'écran passait sous un certain seuil, assez élevé, d'où ce sentiment d'omniprésence.
Patch appliqué et pushé sous Github.
