### ISSUE TITLE
Distinguer le mode de création des groupes d'élèves et des classes

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#68]
Dans la liste des groupes d'élèves et classes, afficher si le groupe ou la classe a été créé manuellement, ce qui permet à l'admin de l'établissement de faire le ménage plus facilement en fin d'année scolaire.
Dans le pire des cas, afficher la date / heure de création sur le tableau car les groupes/classes créés automatiquement auront sensiblement la même heure de création, contrairement aux groupes créés manuellement.
De même, ne pas afficher la case à cocher pour les groupes et classes créés automatiquement afin de rendre impossible leur suppression.

**Comment by HuguesGithub** [comment]
Les classes et groupes créés manuellement seront signalés par un fond verdâtre.
L'ensemble des classes et groupes pourront être sélectionnés afin de pouvoir éventuellement être édités.
L'accès à la popup de suppression sera possible même si une classe ou un groupe créé automatiquement a été sélectionné. Le message d'erreur surviendra lors de la confirmation de la suppression.

La distinction étant possible, on n'affichera pas la date et l'heure de création des classes et groupes.

**Comment by HuguesGithub** [comment]
Pour mémoire, la distinction entre les entités créées par l'académie et celles créées localement se fait via la variable "date_last_maj_aaf" qui est renseignée pour celles créées par l'académie.
