### ISSUE TITLE
Afficher la date de création des groupes libres directement sur le tableau qui liste les groupes d'élèves

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#69]
Ce qui permet de faire plus facilement le nettoyage (sans avoir besoin de cliquer sur chaque groupe pour voir sa date de création).

**Comment by HuguesGithub** [comment]
La colonne "Date de création" est ajoutée entre les colonnes "Groupe libre" et "Nb de membres".
