### ISSUE TITLE
Rendre possible le renommage du nom d'un groupe d'élèves ou d'une classe qui a été créé automatiquement et aussi d'un groupe libre

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#70]
et ne pas que ce nouveau nom (renseigné manuellement) soit écrasé après chaque mise à jour ;)

**Comment by HuguesGithub** [comment]
Nécessite une API REST pour les regroupements dans le Service Annuaire.
Ouverture de l'issue correspondante #87

**Comment by HuguesGithub** [comment]
Interface pour Groupes Libres mise en place. Seul le libellé peut-être modifié.

**Comment by HuguesGithub** [comment]
Interface pour Classes & Groupes d'élèves mises en place. Seul le libellé peut être modifié.

**Comment by HuguesGithub** [comment]
Interfaces modifiées de façon à pouvoir modifier les champs éditables lors d'une création.
Todo : Vérifier que l'update se fait bien pour les classes et les groupes d'élèves, une fois le #87 résolu.
Todo : Mettre la valeur par défaut à la liste déroulante. created_by à retourner par l'api. En attente #87.
