### ISSUE TITLE
Créer un niveau de classe "mixte" (pour s'adapter aux classes multi-niveaux du primaire)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#72]
![creer niveau mixte](https://cloud.githubusercontent.com/assets/7963908/16762013/f6f6d9f4-4822-11e6-85da-9bcd670c7e6d.png)

**Comment by HuguesGithub** [comment]
Il faut alimenter la table niveau pour y insérer cete nouvelle entrée.
Ouverture de l'issue #89 sur service-annuaire.

**Comment by dlacroix** [comment]
Le multi niveau est maintenant géré
