### ISSUE TITLE
Question concernant la suppression du créateur d'un groupe libre

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#74]
Quand le créateur d'un groupe libre est supprimé du groupe (exemple en cas de départ à la retraite du créateur) à l'aide de la poubelle  ou si son compte utilisateur est simplement supprimé, que se passe t-il au niveau du champ "créateur du groupe" ? Y a t'il un impact en cas du suppression du créateur du groupe (des notifications envoyées uniquement au créateur du groupe ? )
Il faudrait alors : 
- soit prévoir que le créateur du groupe puisse être modifié, et si oui, par qui ? seulement par lui-même peut-être pour qu'il puisse transmettre l'administration du groupe libre à un tiers avant de son départ en retraite par exemple ?
- soit prévoir d’interdire la suppression du créateur du groupe (retirer de la poubelle)
  ![ex createur supprime du groupe](https://cloud.githubusercontent.com/assets/7963908/16766597/51d4eb28-483b-11e6-86a1-728b1532ef6e.png)
  ![exemple suppression possible du createur](https://cloud.githubusercontent.com/assets/7963908/16766602/5633ca7c-483b-11e6-802a-c770d4c0e302.png)

**Comment by heleroy** [comment]
Suite à nos échanges : 

- prévoir que seul l'admin peut avoir la possibilité de rechercher et ajouter des utilisateurs de n'importe quel établissement
- depuis la fenêtre de création d'un groupe libre, l'admin peut choisir de céder à un autre admin sa place d'admin
- les membres d'un groupe libre ne peuvent voir que la liste des membres du groupe  mais ne pas les supprimer/retirer du groupe : seul l'admin peut supprimer/retirer des membres, ou aussi, l'utilisateur concerné peut se retirer lui-même. L'admin ne peut pas se retirer lui-même du groupe sinon l'interface doit lui imposer l'affichage de la fenêtre de création du groupe libre pour qu'il définisse un nouvel admin à sa place.

**Comment by HuguesGithub** [comment]
- [ ] n'afficher les champs latéraux de recherche seulement si l'utilisateur est admin du groupe libre
- [ ] L'admin peut céder sa place à une autre personne : En attente issue annuaire qui retourne l'identifiant de l'admin courant.
- [ ] Empêcher la suppression d'autrui à un membre du groupe libre.
- [x] L'admin ne peut pas être supprimé du groupe sur l'interface -> enlever la poubelle de l'admin
- [ ] Lors de la création d'un groupe libre, il faudrait ajouter à ce groupe libre l'administrateur choisi ?
