### ISSUE TITLE
dans la liste des membres d'un groupe libre, afficher le profil du membre (élèves / enseignant etc...) et un moteur de recherche +  cases a cocher et check all si on veut pouvoir proposer une suppression massive de comptes

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#75]
![exemple suppression possible du createur](https://cloud.githubusercontent.com/assets/7963908/16766655/9377ff0c-483b-11e6-8e67-a93fa065d3e3.png)

**Comment by HuguesGithub** [comment]
- [ ] Afficherle profil du membre : cette information n'est pas remontée au niveau des données. A vérifier si elle est ne serait-ce que stockée.
- [x] Ajouter une barre de recherche
- [ ] Suite à l'ajout de la barre de recherche, repenser l'entête du tableau
- [ ] Ajout cases à cocher et suppression massive... Ca implique supprimer le bouton poubelle et tous les remplacer par un système de cases à cocher et un bouton d'action sur la sélection.

**Comment by HuguesGithub** [comment]
Modification de l'interface.
Mais les différents points sont pris en compte.
