### ISSUE TITLE
Prévoir la possibilité de demander son inscription à un groupe libre

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#76]
pour profil élèves et autres

**Comment by HuguesGithub** [comment]
Un utilisateur qui ne fait pas partie d'un groupe peut le rejoindre.
Si le distingo doit être fait entre groupe privé et groupe public, la différence se porte sur le fait que l'inscription n'est pas automatique. Prévoir un statut pending...
- [ ] mise en place de l'interface.
- [ ] Ne pas pouvoir refaire de demande d'inscription si une demande précédente est toujours pending.

**Comment by HuguesGithub** [comment]
Le statut public/privé pour un groupe libre n'étant pas encore défini, lorsque l'utilisateur fait une demande pour rejoindre un groupe libre, il est pour le moment automatiquement ajouté.

**Comment by TestsCGI** [comment]
Issue mère : #159

**Comment by TestsCGI** [comment]
Évolutions groupes libres rentrée 2017 :
(1) Possibilité de rendre privé un groupe libre lors de sa création / édition :
Lors de la création d'un nouveau groupe libre, celui-ci est par défaut Public.
Ajout sur la pop-up de création d'un groupe libre d'une case à cocher : "Privé". 
Par défaut, la case est décochée.

(2) Possibilité de faire une demande d'inscription à groupe libre privé :
Un utilisateur non membre d'un groupe libre privé ne peut accéder à la liste des membres de groupe, c'est à dire :
- pas d'affichage de la liste des membres du groupe
- pas de possibilité d'utiliser la recherche sur les membres du groupe
L'utilisateur peut demander à rejoindre le groupe :
ajout à droite de l'écran, au-dessus du bloc des utilisateurs, d'un bloc avec possibilité de rejoindre le groupe et précisant que l'appartenance au groupe est soumise à validation par l'administrateur du groupe libre

**Comment by HuguesGithub** [comment]
Suite à la reprise de l'interface, le concept de groupe libre public/privé a été abandonné.
Lorsqu'un utilisateur arrive sur la page de détail du groupe, il ne voit pas le détail. Il a la possibilité de faire une demande d'adhésion au groupe (éventuellement à l'annuler).
L'administrateur peut accepter ou refuser cette adhésion.
