### ISSUE TITLE
Création des groupes libres : proposer à l'admin du groupe de rendre son groupe accessible à tous ou accessible sur validation après demande d'inscription

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#77]
Prévoir cela sur la fenêtre de création du groupe, ainsi que des boutons pour valider / refuser la demande d'inscription de tel ou tel membre au niveau de la liste des membres du groupe libre (voir issue #76

**Comment by TestsCGI** [comment]
Issue mère : #159

**Comment by TestsCGI** [comment]
Évolutions groupes libres rentrée 2017 :
En cliquant sur le nombre de demandes d'inscription en attente affiché dans une bulle dans la colonne du nombre de membres dans la liste des groupes libres, accès à une nouvelle interface permettant de gérer les demandes d'inscription par utilisateur / par nom de groupe libre.
La demande peut être validée ou refusée.
Sa validation permet au demandeur de devenir membre du groupe libre privé et d'accéder à la liste des membres du groupe libre ainsi que les contenus existants (docs / blog) du groupe libre (cf. issue #76)
En cas de refus, l'utilisateur demandeur le visualise dans la colonne Statut de la liste des groupes libres (cf. issue #76)

**Comment by HuguesGithub** [comment]
Notion de groupe libre public/privé abandonné.
Dans la liste des membres d'un groupe est affiché une cartouche pour signifier les membres en attente d'adhésion. Sur cette cartouche sont disponibles pour l'administrateur, deux boutons l'un pour accepter, l'autre pour refuser.

En cas de refus, l'utilisateur n'a plus le statut "en demande d'attente". S'il est membre, l'astérisque présent devant "Membres" est présent. S'il va sur le détail il voit la liste des membres. S'il ne l'est pas, il n'a rien de tout ça et peut à nouveau faire une demande d'adhésion.
