### ISSUE TITLE
Proposer à un élève la possibilité de rechercher un groupe libre et de demander à s'y inscrire

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#78]
Cela implique que l'élève puisse aussi avoir la tuile "administration" et que lorsqu'il accède au panel administration, il puisse voir uniquement la gestion des groupes libres pour pouvoir les rechercher et demander à s'inscrire à un groupe libre.

**Comment by TestsCGI** [comment]
Issue mère : #159

**Comment by HuguesGithub** [comment]
Techniquement réalisé, modulo le fait qu'un élève ait le droit d'accéder à l'interface de l'admin panel.
