### ISSUE TITLE
bug d'affichage de la liste déroulante de l'établissement (sans fin sur la droite) d'ajout de role sur un user

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-admin-panel#84]
depuis le profil tech cf capture
![capture du 2016-07-21 16-36-16](https://cloud.githubusercontent.com/assets/7963908/17026741/6aa2b798-4f61-11e6-82f6-bf60324298d2.png)

**Comment by HuguesGithub** [comment]
Non reproduit en prod.
Le fait qu'il soit "sans fin" ne doit pas empêcher son affichage et une sélection.
S'il est "sans fin", c'est parce qu'une de ses entrées et trop longue.
Idéalement, le dérouler pour voir de qu'elle il s'agit.
