### ISSUE TITLE
liste users

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#86]
- [x] Admin_Etab : filtrer par profil
- [x] pareil et aussi par etab

**Comment by HuguesGithub** [comment]
http://stackoverflow.com/questions/20849804/filter-by-multiple-columns-with-ng-repeat

**Comment by HuguesGithub** [comment]
Ajout de listes déroulantes en entête de colonne pour lancer une recherche restreinte. Ce n'est pas un filtre, c'est une requête.
En l'état, pas possible de multi-sélectionner un établissement ou un profil.

**Comment by HuguesGithub** [comment]
Par ailleurs, la requête s'appuye sur les libellés et pas les identifiants techniques. Ca n'est pas optimal et pose parfois problèmes (le profil Elèves retourne des profils Responsables d'élèves).
Les données profil_id et code_uai ne sont pas disponibles dans les données retournées par l'Annuaire.
