### ISSUE TITLE
Test V3 - 2016 : Profil de l'utilisateur non mis à jour suite modification rattachement classe

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#87]
Dans la gestion des groupes et classes, un enseignant est détaché d'une de ses classes.
Dans la gestion des utilisateurs, après modification de ses rattachements, il apparaît toujours rattaché à la classe.

**Comment by HuguesGithub** [comment]
Après analyse, ce n'est pas un bug technique. Eventuellement fonctionnel.

Le user utilisé pour déclencher cette anomalie avait un profil Enseignant et devait avoir aussi un profil CPE (Directeur d'établissement, Documentaliste ou EVS).
Or, lorsque l'on va sur l'interface des profils d'un utilisateur, et que cet utilisateur est CPE, on affiche toutes les classes et tous les groupes d'élèves rattachés à l'établissement.

Aussi, lorsque l'on revient sur l'onglet de profil de l'utilisateur et que le groupe dont on vient de le détacher s'affiche toujours, ce n'est pas parce que le profil n'a pas été mis à jour, c'est parce que, en tant que "CPE", l'information s'affiche.

**Comment by TestsCGI** [comment]
Retesté pour un enseignant : OK
Le groupe duquel l'enseignant a été détaché ne fait plus partie de la liste des regroupements de l'enseignant
