### ISSUE TITLE
Test V3 - 2016 : Affichage de la gestion des utilisateurs / groupes / classes KO sous IE

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#88]
Priorité 1

**Comment by HuguesGithub** [comment]
Reprise des différents écrans rencontrant le même problème.
Le bug venait du fait qu'était utilisé une instanciation de l'objet Map qui n'existe qu'à partir de IE 11.
L'anomalie avait été repérée sur IE 10.

**Comment by TestsCGI** [comment]
Test OK

**Comment by TestsCGI** [comment]
Test OK sur la gestion des utilisateurs 
Test KO sur la gestion des groupes et classes

**Comment by HuguesGithub** [comment]
Suite passage v4, plus de problèmes rencontrés.
