### ISSUE TITLE
Test V3 - 2016 : Affichage des données de l'alimentation automatique

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#93]
Lorsqu'au niveau des données établissement, on clique sur alimentation automatique, le portail s'affiche à nouveau au lieu d'afficher les données liées au chargement des données de l'annuaire. Lien à corriger.

**Comment by HuguesGithub** [comment]
Le lien ressemble à ceci :
https://www.laclasse.com/annuaire/?domaine=v3.laclasse.com

Le domaine est-il pertinent ?
Par ailleurs, si on saisi manuellement (ou copie/colle) le même lien dans l'url, et que l'on s'identifie, si on clique sur le lien de l'admin panel, on parvient bien cette fois à l'écran attendu.

**Comment by HuguesGithub** [comment]
TODO : En attente correctif [#52 - annuaire-ent](https://github.com/laclasse-com/annuaire-ent/issues/52)

**Comment by TestsCGI** [comment]
OK
