### ISSUE TITLE
Test V3 - 2016 : Rafraîchissement bannière établissement

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#94]
Après une opération d'ajout / modification d'un élément de l'admin panel, même si le message de confirmation de création / modification de l'élément s'est bien affiché, l'ajout / modification n'est pas visible à moins de relancer manuellement le rafraîchissement.
Ex. modification du fichier bannière sur les informations de l'établissement

**Comment by TestsCGI** [comment]
Autre exemple : ajout de ressource numérique : la ressource ajoutée est visible par l'utilisateur connecté avec FF par ex. S'il se déconnecte et se reconnecte avec IE : la nouvelle ressource n'est pas listée alors qu'elle est bien présente lorsqu'il se reconnecte avec Chrome

**Comment by TestsCGI** [comment]
La bannière de l'établissement n'est pas rafraîchie après modification.
Elle reste en mémoire cache.

**Comment by HuguesGithub** [comment]
Confère  #127

**Comment by dlacroix** [comment]
Plus de bannière car utilisée nul part pour l'instant
