### ISSUE TITLE
Test V3 - 2016 : Informations établissement - Géolocalisation - Mise à jour carte

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#95]
Dans l'onglet géolocalisation, une fois les coordonnées latitude et longitude mises à jour, et après avoir cliquer sur Modifier, la carte ne s'affiche pas / n'est pas mise à jour (elle n'était pas affichée avant d'avoir renseigné les coordonnées).

**Comment by HuguesGithub** [comment]
Cet onglet n'existe plus et cette information n'est plus présentée.
