### ISSUE TITLE
Test V3 - 2016 : Gestion des utilisateurs - Edition des informations générales d'un utilisateur

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#98]
Lorsqu'on ajoute le numéro de téléphone sur l'onglet des informations générales d'un utilisateur, quelque soit le type de téléphone sélectionné c'est le type MAISON qui est retenu et qui est affiché

**Comment by HuguesGithub** [comment]
Problèmatique Annuaire.
Un contrôle foireux se fait sur le type_telephone_id

**Comment by TestsCGI** [comment]
OK
