### ISSUE TITLE
Test V3 - 2016 : Gestion des utilisateurs - Message de suppression d'une relation lors de la création d'une nouvelle relation

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#99]
Lorsqu'on supprime une relation puis qu'on souhaite la remplacer par une nouvelle relation, après avoir cliqué sur le bouton d'ajout d'une relation, le message "la relation a bien été supprimée" est affiché dans la fenêtre d'ajout de la relation. Ce message est également affiché en arrière plan (dans l'écran principal).
Ceci n'est pas bloquant pour la création de la nouvelle relation.

**Comment by HuguesGithub** [comment]
Suppression de la balise qui affichait le message.

**Comment by TestsCGI** [comment]
OK
